### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by nilsreichardt** [jeremylandon/string-similarity#4]
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by jeremylandon** [comment]
I will do when null safety will out of beta :hammer:

**Comment by nilsreichardt** [comment]
@Golapadeog Null safety is out of beta :) Since Flutter 2 it's stable 👍

**Comment by nilsreichardt** [comment]
@Golapadeog I created a PR: #5. Please check everything

**Comment by Zeswen** [comment]
Waiting for this to update our application to Flutter 2.0!

It would be awesome to have it ASAP. Thank you for your great work :)

**Comment by jeremylandon** [comment]
> @Golapadeog I created a PR: #5. Please check everything

Thanks for your PR, I check it as soon as possible :ok_hand:



> Waiting for this to update our application to Flutter 2.0!
> 
> It would be awesome to have it ASAP. Thank you for your great work :)

An update will arrive at the end of the week :rocket:

**Comment by nilsreichardt** [comment]
#5 is merged :)

**Comment by jeremylandon** [comment]
@Zeswen @nilsreichardt 
:tada: The new version of string_similary with null safety compatibility is avialable https://pub.dev/packages/string_similarity

:bulb: Please note that null can be used by methods to compare string and doesn't throw exception
* null / null = 1.0
* null / "a" = 0.0
* "a" / null = 0.0

:pencil: the documentation has been updated accordingly
