### ISSUE TITLE
Don't really works

### ISSUE THREAD

**Issue by incrediblezayed** [jeremylandon/string-similarity#8]
I was trying to find the best match of the string but it didn't work,
I gave it a text 'hassan' and a list of text which had 2 elements which contained the exact word 'hassan' in the beginning,
but it turned out, the results were 'drkaleem' and 'drvijay'

Can you help me out here?
`      var bestMatch = StringSimilarity.findBestMatch(
                 'hassan',
                 aListOfStringHere);
`

**Comment by jeremylandon** [comment]
With your case: 

```

final matches = StringSimilarity.findBestMatch( 'hassan', ['hassan', 'drkaleem', 'hassan', 'drvijay']);

// matches.bestMatch => ('hassan'[1.0])

// matches.bestMatchIndex => 0

// matches.ratings => [  Rating ('hassan'[1.0]) , Rating ('drkaleem'[0.0]) , Rating ('hassan'[1.0]) , Rating ('drvijay'[0.0]) ]

```

You can find all best matches with **ratings** property (if you need, you can order the collection by rating score) or the first/default best match with **bestMatch** property
